image: node:11

before_script:
  - apt-get update -qq
  - apt-get install -qq git
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SERVER_KEY" | base64 -d)
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

stages:
  - install
  - build_production
  - deploy_production

cache:
  paths:
    - node_modules/

install:
  stage: install
  script:
    - npm install --verbose -f
  artifacts:
    paths:
      - node_modules/

build_staging:
  stage: build_staging
  only:
    - staging
  script:
    - npm run stage

build_prod:
  stage: build_production
  only:
    - master
  script:
    - npm run prod

deploy_staging:
  stage: deploy_staging
  only:
    - staging
  script:
    - ssh ${SERVER_USER}@${SERVER_ADDRESS} "cd ${SERVER_PATH_STAGING} && rm -rf node_modules dist/* tmp"
    - ssh ${SERVER_USER}@${SERVER_ADDRESS} "cd ${SERVER_PATH_STAGING} && git pull origin staging"
    - ssh ${SERVER_USER}@${SERVER_ADDRESS} "source ~/.bash_profile && export NPM_TOKEN=${NPM_TOKEN} && export SECRET_JWT=${SECRET_JWT} && cd ${SERVER_PATH_STAGING} && nvm use --delete-prefix && git checkout staging && npm ci --verbose && npm run prod"
    - ssh ${SERVER_USER}@${SERVER_ADDRESS} "cd ${SERVER_PATH_STAGING} && export SECRET_JWT=${SECRET_JWT} && NODE_ENV=staging pm2 restart ./dist/server.js --name staging.antoniodiaz.me --update-env"

deploy_production:
  stage: deploy_production
  only:
    - master
  script:
    - ssh ${SERVER_USER}@${SERVER_ADDRESS} "cd ${SERVER_PATH_PRODUCTION} && rm -rf node_modules dist/* tmp"
    - ssh ${SERVER_USER}@${SERVER_ADDRESS} "cd ${SERVER_PATH_PRODUCTION} && git pull origin master"
    - ssh ${SERVER_USER}@${SERVER_ADDRESS} "source ~/.bash_profile && export NPM_TOKEN=${NPM_TOKEN} && export SECRET_JWT=${SECRET_JWT} && cd ${SERVER_PATH_PRODUCTION} && nvm use --delete-prefix && git checkout master && npm ci --verbose && npm run prod"
    - ssh ${SERVER_USER}@${SERVER_ADDRESS} "cd ${SERVER_PATH_PRODUCTION} && export SECRET_JWT=${SECRET_JWT} && NODE_ENV=production pm2 restart ./dist/server.js --name antoniodiaz.me --update-env"
